### ISSUE TITLE
Steps I did in Excel and you should try to do in R

### ISSUE THREAD

**Issue by jmarkgraf** [mberneaud/PairAssignment3#2]
Hi Malte,

Here I below list the preparatory steps that I did in Excel and you could try to do in R:
- **Change the label names**: The ones I used are the following - IDMunicipality; NameMunicipality; ElectionDate; ElectionType; ProfPolitician; NumberEligVoter; NumberVoter; InvalVotes; ValVotes; NameCandidate1; SexCandidate1; DateInauguration; ProfessionCandidate1; YearBirthCandidate1; PartyCandidate1; VotesCandidate1; VotesRest (in this order).
- **Title of Mayor**: Extract "Dr. " from NameCandidate1 column and create new column that indicates if mayor has Dr. title.
- **Re-Election Dummy**: Create Dummy for Re-Election of Mayor (1 = if yes)

**Comment by jmarkgraf** [comment]
Another thing that I haven't had the chance to look at yet is the following: The dataset is ordered by municipality and by date (second order). We need to know in which term each candidate is. So, we would need an additional column that starts counting whenever there is a new candidate in a given municipality (1 for first term, 2 for second term etc.).
I already have created variables for (1) contested election (dummy); (2) vote shares; (3) victory margin; (4) indicator for close races (dummy).

**Comment by mberneaud** [comment]
Thanks for writing this all down. I'll get to it then!

**Comment by mberneaud** [comment]
I created a dummy variable indicating whether or not  the candidate and I would like to know whether you removed the "Dr." from the name subsequently?

**Comment by jmarkgraf** [comment]
Yes, I did! And keep in mind to also remove the space that goes with the Dr.. This is important for the matching between names in the two datasets!

**Comment by mberneaud** [comment]
Alright, that's what I did now. Thanks for the quick response.
