### ISSUE TITLE
Upload of R File

### ISSUE THREAD

**Issue by jmarkgraf** [mberneaud/PairAssignment3#3]
Hi Malte, could you please also upload the R file for the Mayor Election Dataset? This would make it easier to see where you are at the moment! Thanks!

**Comment by mberneaud** [comment]
I do not have any particular R file I used. Instead, all the analysis I conducted is done directly within the RMarkdown document. I decided to do it this way to stay as close as possible to Christopher's requirement of using literate programming. Hence, I wanted to have the code and the write-up right next to each other. 

I just got an Internet connection just now, so I merged in your changes with mine and pushed them to the repo. You should see what other changes I've made. As a result, we have two codes for merging now, but I'll delete mine in a second and make another push.

**Comment by jmarkgraf** [comment]
Okay, I will leave the decision on that to you as the Election data manipulation is your part. Please let me know in case you might struggle with any of the steps as I have implemented all of them already (in a slightly different way, but there are always more than one way to skin a cat!).

**Comment by mberneaud** [comment]
I'll keep this issue open to remind myself to copy over my R code from the Rmarkdown over to a single R file for bug-searching.

**Comment by jmarkgraf** [comment]
Okay, thanks. Would be great if you could do this soon, so that I can check it!

**Comment by mberneaud** [comment]
Good morning Jonas, 

I now added a standalone R file which contains my code on the cleaning and subsetting of the election data set. 

Have a nice day!

**Comment by jmarkgraf** [comment]
Opened a new issue in the new repo with my comments!
