### ISSUE TITLE
Renaming Variables in Sparkassen Dataset

### ISSUE THREAD

**Issue by jmarkgraf** [mberneaud/PairAssignment3#4]
Hi Malte, could you quickly clarify what you did when renaming the variables of the Sparkassen dataset (in the Markdown document) and how this will affect the steps that I conducted in the two R files for the Sparkassen data frame? I think I used the old variable names, so I now have to update all the R files? In this case, I would suggest that we do not change variable names for the Sparkassen data frame, in particular since we only need the information of board member names for the merge with the Mayor Election data frame. Let me know what you think!

**Comment by mberneaud** [comment]
I slightly changed the names of the Sparkassen dataset away from what you used in your R files to achieve more consistency in the naming of the different variables, which, I must admit in hindsight, might have been slightly less than ideal. 

However, I copied over the steps which you conducted seperately in your .R files over into the RMd document at the relevant positions and also renamed the variables in such a way that they are consistent with my different renaming. The different code chunks ran individually when I tested them on the plane and also rendered without any problems. I'll check that again as in a minute, debug it, if necessary and commit the changes again. 

As for the names of the mayors, I agree that we should only keep parts of the data set. However, as our observation is mayor-elections, as noted in Christopher's response to our second assignment, shouldn't we keep the years in the _Sparkassen_ dataset, too? This way we could identify whether mayors were in the board of a local Sparkasse during an election year. Or do you think the timing of the mayor's membership of the  board is irrelevant? I.e. mayors could have already retired from the board during the election year. However, this leaves open the possibility of us mis-matching a person who was a mayor at some point, and who became a member of the board after he retired from office. E.g. Horst Maier was Mayor of Altlöttel from 1992 to 2002, and  subsequently became the chair of his  local Sparkassen board in 2005. If we do not account for the year, we would associate this person with a Sparkassen board position which should not have influenced his political career. 

What are your thoughts on that?

**Comment by jmarkgraf** [comment]
About the timing when a mayor was on the board: Your point is valid and is central part of the paper that I write with Guillermo, but it is not as easy to implement. Usually the selection process of board members takes some time, thus it does not coincide with the election of the new mayor, but he might become member of the Sparkasse only 1-2 years later. As far as I can see, the implementation of that would take some time and in general we can approximate board membership of mayors by just matching the two datasets by names (rather than name-year observations). Of course this is not the perfect measure, but considering that the assignment is due in 12 hours I see other, more urgent things we have to work on in the Election dataset and on the write-up in order to complete the assignment on time.

**Comment by mberneaud** [comment]
Okay to get that out of the way: the assignment deadline has been postponed by Christopher to Tuesday 12am because of all the trouble there was with Hertie Wifi and connecting to GitHub. Hence, we are not under _that_ much pressure anymore. He announced it on the issues page of the course repo [link](https://github.com/HertieDataScience/SyllabusAndLectures/issues/99). If you "watch" the repo, you can subscribe to receive notifications whenever a new issue is opened on the issues page of the repo.

However, I would prefer to get the assignment out of the way today so I can enjoy my weekend without having to worry about it.

**Comment by jmarkgraf** [comment]
Ah, okay. That's good news! But: Exactly my thought! Let's try to get rid of the assignment today (at least the big things). Minor stuff can then still be edited in the next days!
