### ISSUE TITLE
R Code: Term of Mayors

### ISSUE THREAD

**Issue by jmarkgraf** [mberneaud/PairAssignment3#6]
Hi Malte, 

Here is the SpellCount R Code. To use it, you need to get the DataCombine package from Christopher's github page (devtools::install_github("christophergandrud/DataCombine").
# Terms of Mayors

MayorElection$FakeVar <- 1
MayorElection <- CountSpell(MayorElection, TimeVar = "ElectionDate", 
                        SpellVar = "FakeVar", GroupVar = "NameCandidate1", 
                        NewVar = "TermMayor", SpellValue = 1)

**Comment by mberneaud** [comment]
Hm, the code does not work for me and terminates with the following error message: 

```
Error: SpellValue must be the same class as SpellVar
In addition: Warning message:
In if (class(SpellValue) != class(data[, SpellVar])) stop("SpellValue must be the same class as SpellVar",  :
  the condition has length > 1 and only the first element will be used
```

It persists even if I coerce FakeVar into an integer, or I coerce SpellValue to a numeric value, which is the same as the FakeVar.

I guess that's not terribly important at the moment, but if the code runs on your machine, you could run the code once and save the resulting data set as a csv to our share dropbox.

**Comment by jmarkgraf** [comment]
I can do that later, but I think it might not be as central (as you already mentioned). Could you briefly update me where you are at the moment and what we need to do by the end of the day? I'm very busy today, so it would be good if you let me know what is needed from my side!

**Comment by mberneaud** [comment]
The one thing you could do is to include regression output tables you showed to me in class yesterday into the inference section of our text. Could you also send me the URL where you downloaded the election data set? For the sake of reproducibility, I'd like to include an R file downloading the excel sheet along with the data. 

Over the course of the morning / early noon, I'll 
- ~~add another one or two graphs for my descriptive section~~
- ~~try to figure out how to make the graphs smaller in the rendered document (ideally in the first code chunk which sets the global options)~~
- delete unnecessary files from the repo and improve the README, so that relevant files are easy to find

Then I'll 
- proofread the document 
- check the word count, trim some stuff here and there if necessary. 

As a last step, I'd ask you to proofread the text for a final revision, make changes where necessary and send the repo link to Christopher.

**Comment by jmarkgraf** [comment]
I had a brief look at what you have done. Here are my comments:
- Dummy for contested election: Have a look at what "VotesRest" means - it's not all other candidates' votes. You should rather take "NameCandidate2".
- Party Affiliation: We are interested in the two main parties SPD and CSU. Is there a considerable share of FDP mayors? For "Freie Wähler" we can't treat them as a real party as they are more independent lists. My suggestion would be to categorize in SPD, CSU and others.
- Subsetting & re-election dummy: Have you had a look at the output if it implemented your steps correctly? Maybe cross-check a number of lines. How many observations do we lose by excluding all elections that required a run-off completely?

Have you implemented the steps required to run the regressions, i.e. lagged vote share of incumbent, lagged board membership, and lagged sex of incumbent? As far as I can see we are at exactly 1500 words now, so we either need to cut severely or present the regressions without really discussing them. Please let me know once I can implement the regressions.

Regarding the source of the election data: As once mentioned, the dataset is not accessible from a website. We bought it from the Bavarian state statistical office. That's why it should not be circulated!

**Comment by mberneaud** [comment]
> Dummy for contested election: Have a look at what "VotesRest" means - it's not all other candidates' votes. You should rather take "NameCandidate2".

Regarding this, if you have a codebook for the dataset, could you please share it on our Dropbox folder? Regardless, I changed the loop to consider the name of the second candidate instead. 

> Party Affiliation: We are interested in the two main parties SPD and CSU. Is there a considerable share of FDP mayors? For "Freie Wähler" we can't treat them as a real party as they are more independent lists. My suggestion would be to categorize in SPD, CSU and others.

I see your point and changed my code accordingly.

> Subsetting & re-election dummy: Have you had a look at the output if it implemented your steps correctly? Maybe cross-check a number of lines. How many observations do we lose by excluding all elections that required a run-off completely?

We lose about 1,5k observations out of 3,5k originally, which is indeed quite harsh. I suggest we only exclude elections which required run-offs then and don't worry too much about the fact that run-off elections might overstate the number of votes a candidate received, as I am not sure whether I'll be able to implement a matching of votes / candidate names between election rounds (like you suggested in class) without investing a lot of time.

> Have you implemented the steps required to run the regressions, i.e. lagged vote share of incumbent, lagged board membership, and lagged sex of incumbent?

I did that just now. Thanks for reminding me.

**Comment by mberneaud** [comment]
Add: Excluding only those elections which required run offs (ElectionType 3), we retain 2559 observations.

**Comment by jmarkgraf** [comment]
Have you pushed your changes? I can't find them in the file on GitHub. Would be great if you could push them asap, so that I can implement the last steps as I have to prepare a presentation for tmrw this afternoon!
There is no such thing as a codebook, but if you compare votes of the first best loser with VotesRest, you can see that VotesRest are much less and seems to be a residual category.

**Comment by mberneaud** [comment]
Did the push just now.

**Comment by jmarkgraf** [comment]
Have you tried the regressions? I just did and they don't make any sense. Female incumbents are more likely to be re-elected, mayors with high vote shares in previous elections are less likely to be re-elected. Are you sure that you did all transformations correctly? It would be helpful to have a single R document to check each step now. Unfortunately I don't have the time to double check each step and I think we spend way too much time for a 10% assignment on this paper anyways already. Please let me know if I should just describe those, lets say "unexpected", results or what your suggestion is. I think it was definitely not ideal to wait with the regressions until the evening before we need to submit as it takes a lot of time to specify correctly and check for mistakes in the transformations. This is however something we can't change anymore. It however gives me a headache to report those regression outputs that are complete non-sense...

**Comment by jmarkgraf** [comment]
Furthermore, is there a good way to report regression tables in Markdown PDFs?

**Comment by jmarkgraf** [comment]
So, I thought about it, checked a bit your transformations and decided that I will take it as it is, comment it and openly admit that there are severe weaknesses. I furthermore changed one of your transformations (rescaled). I upload the updated file in 15 minutes.
Could you please compile a new R file with all your transformations and steps, so that we can check each step? This is much easier than looking for each step between the written lines in the Rmd file. Furthermore, please clarify how the "Gender variable" is coded. Seems it is 1 for men? Thanks!

**Comment by mberneaud** [comment]
I haven't tried the regressions yet and left it to you. I am it in a group meeting for another class right now, but I'll extract my code from the R-Markdown afterwards and check it for errors. So far, I have checked whether most of the code worked on a superficial level, but didn't do any cross-tabulations or such. 

As for the regression tables, a good package which produces pretty tables is stargazer. If you have the code for the regression in the Markdown, I can implement it easily as I also used it in my master thesis. 

Regarding the coding of gender, I did not change the coding of the variable. Right now, it's a factor with two levels: m and w. 

Anyways, I'll look into this as soon as I am done with my meeting. And if this assignment is not perfect in the end, so be it. As you said, we probably invested way too much time into this as is.

**Comment by jmarkgraf** [comment]
Let's just leave it as it is for now! Thanks for the hint with stargazer. I first failed to use the "asis" part. Now it works fine!
Could you have a final look at the formatting, word count and last small edits?
I think we can fine-grain everything for the next assignment. I could have a look at the different steps you took and try to understand why my own subset has different features than the one that we both created now. For that, a single R file would be good.
If you want, I can have a final look at it tonight, but for now I really need to prepare my presentation for tomorrow. I think the assignment is okay, but not perfect. But then its also just 10%!

**Comment by mberneaud** [comment]
Alright, let's do it like you proposed and keep most of the refinements and bug hunting for the final assignment. 

I'll have a look at the final document ASAP and make some final changes if needed. I suggest I just send it to Christopher afterwards in order to avoid another round of back-and-fourth.

**Comment by jmarkgraf** [comment]
Okay, perfect. Please copy me in the mail! Thanks!

**Comment by mberneaud** [comment]
The mail delivered without any errors, so I suppose you received it. I'll close this issue now.
